Model:
  customObjects:
    class: []
    functions: []
    module: []
  kerasmodel: keras_models_full/vgg16_model.h5
OutputDir:
  simDataDir: simData/
SplitLayer:
  split: block3_conv2
Task:
  value: 0
TestInput:
  batch_size: 64
  dataset: imagenet
  testdir:
    annotations: []
    images: largeTest_resized
    testNames: []
taskParams: taskParams.yml
